name: Cache Java and Java Dependencies
description: This action allows to cache both Java and Java Dependencies on the pom.xml file

inputs: 
  java-version:
    description: Java version to use
    default: 11
    required: true

runs:
  using: composite
  steps: 
    - name: Setup Java version ${{ inputs.java-version }}
      uses: actions/setup-java@v4
            with:
              distribution: 'adopt'
              java-version: ${{ inputs.java-version }}
              cache: 'maven'
    - name: Install Dependencies
      run: mvn dependency:go-offline