name: Cache Java and Maven Dependencies
description: This action allows caching both Java and Maven Dependencies based on the pom.xml file

inputs: 
  java-version:
    description: 'Java version to use'
    default: '11'
    required: true
  working-dir:
    description: The working directory of the application
    default: .
    required: false
  target-env:
    description: ' "dev" or "prod". Controls whether dev dependencies are installed '
    default: dev
    required: false

outputs:
  installed-deps:
    description: Whether dependencies were installed or not
    value: ${{ steps.cache.outputs.cache-hit != 'true' }}

runs:
  using: 'composite'
  steps: 
    - name: Setup Java version ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: ${{ inputs.java-version }}
        cache: 'maven'
        target-env: ${{ inputs.target-env }}

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: ${{inputs.target-env == 'dev' && 'mvn dependency' || 'mvn dependency --omit=dev' }}
      shell: bash
      working-directory: ${{ inputs.working-dir }}
