name: 17 - Custom Actions - Composite
run-name: 17 - Custom Actions - Composite

on:
  workflow_dispatch:

env:
  working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Setup Java & Maven dependencies
        uses: padmanabhansaravanan/cache-deps@v1
        with:
          java-version: 11
          working-dir: ${{ env.working-directory }}

      - name: Run tests
        run: mvn test

      - name: Build with Maven
        run: mvn clean install
