name: 00-Fetch-Todo-Data
on:
  workflow_dispatch: 

jobs:
  fetch-todo:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Todo Data 📦
        run: |
          # Use curl to fetch the data from the API endpoint
          todo_data=$(curl -s https://jsonplaceholder.typicode.com/todos/1)
          # Print the fetched data
          echo "Fetched Todo Data: $todo_data"
