name: 04-01-Workflow Events

on:
  # push:
  workflow_dispatch:
  # pull_request:
  # schedule:
  #   - cron: '*/5 0 * * *' # Run every 5 min

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "I've been triggered by a(n) ${{ github.event_name }} event."
