name: 04 - Using Actions

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip=true
        
      - name: Run tests
        run: mvn test

      - name: I will be skipped
        if: ${{ success() }}
        run: echo "I will print if previous steps succeed."
      - name: I will execute
        if: ${{ failure() }}
        run: echo "I will print if any previous step fails."

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: failure()
    steps:
      - name: Send Notification
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const { context, github } = require('@actions/github');

            const repo = context.repo;
            const workflowRunId = context.runId;
            const jobName = context.job;
            const runURL = `${repo.owner}/${repo.repo}/actions/runs/${workflowRunId}`;

            const message = `Workflow "${workflowRunId}" failed on job "${jobName}". Workflow run URL: ${runURL}`;

            github.issues.createComment({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: context.issue.number,
              body: message
            });