name: 05 - Using Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: Whether to execute cache step
        type: boolean
        default: true
      java-version:
        description: Java version
        type: choice
        options:
          - 11
          - 14
          - 17
        default: 11

jobs:
  install-deps:
    runs-on: ubuntu-latest
    outputs:
      deps-cache-key: ${{ steps.cache-key.outputs.CACHE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'adopt'
          
      - name: Calculate cache key
        id: cache-key
        run: echo "CACHE_KEY=deps-maven-repo-${{ hashFiles('**/pom.xml') }}" >> $GITHUB_ENV

      - name: Download cached dependencies
        uses: actions/cache@v3
        if: ${{ inputs.use-cache }}
        id: cache
        with:
          key: ${{ steps.cache-key.outputs.CACHE_KEY }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: mvn dependency:go-offline