name: 08 - Custom Actions - Composite
run-name: 08 - Custom Actions - Composite | env - ${{ inputs.target-env }}

on:
  workflow_dispatch:
    inputs: 
      target-env:
        description: which environment to target for dependency installation
        type: choice
        options:
          - dev
          - prod

env:
  working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Setup Java & Maven dependencies
        uses: ./.github/actions/composite-cache-deps
        with:
          java-version: 11
          working-dir: ${{ env.working-directory }}
          target-env: ${{ inputs.target-env }}

      - name: Run tests
        run: mvn test

      - name: Build with Maven
        run: mvn clean install
