name: 22 - CI CD Pipeline for TodoApp

on:
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Upload jar to folder
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: target/
        
  deploy:
    runs-on: self-hosted
    needs: build

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download web-app content
      uses: actions/download-artifact@v4
      with:
        name: my-artifact
        path: target/
           
    - name: Build Docker image
      run: docker build -t padmanabhan1/todoapp .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push image to Docker Hub
      run: docker push padmanabhan1/todoapp
