name: 22-CI/CD Pipeline for TodoApp

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Custom Action
    - name: Checkout repository and Setup Java
      uses: ./.github/actions/composite-checkout-build

    - name: Build with Maven
      run: mvn clean install -Dmaven.test.skip=true

    - name: Upload jar to folder
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: target/

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and Setup Java
      uses: ./.github/actions/composite-checkout-build
    - name: Test with Maven
      run: mvn -B test
