name: 23-03-Reusable Workflows

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/23-01-reusable-workflows.yaml
    with:
      target-directory: dummmy-dir
  e2e-tests:
    uses: PadmanabhanSaravanan/github-actions-course-example-e2e/.github/workflows/e2e.yaml@main
    needs: deploy
    secrets:
      access-token: ${{ secrets.GH_TOKEN }}