name: KubeConfig

on:
  workflow_dispatch:
      
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Deploy to Kubernetes
      run: kubectl apply -f deployment.yaml
